baseURL = "https://wldomiciano.com/"
languageCode = "pt-br"
defaultContentLanguage = "pt-br"
title = "Wellington Domiciano"
author = "Wellington Domiciano"
disableKinds = ["section", "taxonomyTerm"]
googleAnalytics = "UA-48568115-1"
disqusShortname = "wldomiciano"

[params]
  email = "wldomiciano@gmail.com"
  description = "Blog sobre coisas que tenho aprendido"
  github_username = "wldomiciano"
  twitter_username = "wldomiciano"

[taxonomies]
  tag = 'tags'

[frontmatter]
  date = [":filename", ":default"]

[permalinks]
  posts = ":slug"

[markup.highlight]
  noClasses = false

[markup.goldmark.renderer]
  unsafe = true
