baseURL = "https://wldomiciano.com/"
languageCode = "pt-br"
title = "Wellington Domiciano"
author = "Wellington Domiciano"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]
pygmentsCodefences = true

[outputs]
home = [ "RSS", "HTML"]

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"

[params]
  email = "wldomiciano@gmail.com"
  description = "Blog dedicado a publicação de artigos sobre coisas que tenho aprendido"
  github_username = "wldomiciano"
  twitter_username = "wldomiciano"

[frontmatter]
  date = [":filename", ":default"]
  googleAnalytics = "UA-48568115-1"
  disqusShortname = "wldomiciano"

[permalinks]
  posts = "/:slug/"

[blackfriday]
  hrefTargetBlank = true
