baseURL = 'https://wldomiciano.com/'
defaultContentLanguage = 'pt-br'
title = 'Wellington Domiciano'
author = 'Wellington Domiciano'
disableKinds = ['section', 'taxonomy']
theme = 'default'

[services]
  [services.googleAnalytics]
    ID = 'UA-48568115-1'
  [services.disqus]
    shortname = 'wldomiciano'

[params]
  description = 'Blog sobre coisas que tenho aprendido'
  github_username = 'wldomiciano'
  twitter_username = 'wldomiciano'

[languages.en]
  languageCode = 'en'
  languageName = 'English'
  [languages.en.params]
    description = 'A simple blog to share what I have learned.'
    keywords = ['Programming', 'Tutorials']
    postedOn = 'Posted on'
    updatedOn = 'Updated on'
    readIn = 'Read in English'
    tagLabel = 'Posts tagged with'
[languages.pt-br]
  languageCode = 'pt-br'
  languageName = 'Português'
  [languages.pt-br.params]
    description = 'Um simples blog para compartilhar o que tenho aprendido.'
    keywords = ['Programação', 'Tutoriais']
    postedOn = 'Postado em'
    updatedOn = 'Atualizado em'
    readIn = 'Leia em Português'
    tagLabel = 'Posts com a tag'

[taxonomies]
  tag = 'tags'

[frontmatter]
  date = [':filename', ':default']
  lastmod = ['lastmod']

[permalinks]
  blog = ':slug'

[markup.highlight]
  noClasses = false

[markup.goldmark.renderer]
  unsafe = true
