baseURL = "https://wldomiciano.com/"
languageCode = "pt-br"
defaultContentLanguage = "pt-br"
title = "Wellington Domiciano"
author = "Wellington Domiciano"
disableKinds = ["section", "taxonomyTerm"]
googleAnalytics = "UA-48568115-1"
disqusShortname = "wldomiciano"

pygmentsCodefences = true
pygmentsUseClasses = true

[outputs]
  home = [ "RSS", "HTML"]

[outputFormats]
[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "feed"

[params]
  email = "wldomiciano@gmail.com"
  description = "Blog sobre coisas que tenho aprendido"
  github_username = "wldomiciano"
  twitter_username = "wldomiciano"

[frontmatter]
  date = [":filename", ":default"]

[permalinks]
  posts = "/:slug/"

[blackfriday]
  hrefTargetBlank = true
  noreferrerLinks = true

[markup.goldmark.renderer]
  unsafe= true
