baseURL = "https://wldomiciano.com/"
languageCode = "pt-br"
title = "Wellington Domiciano"
email = "wldomiciano@gmail.com"
description = "Blog dedicado a publicação de artigos sobre coisas que tenho aprendido"
author = "Wellington Domiciano"
github_username = "wldomiciano"
twitter_username = "wldomiciano"

[frontmatter]
date = [":filename", ":default"]
googleAnalytics = "UA-48568115-1"
disqusShortname = "wldomiciano"

[permalinks]
posts = "/:slug/"
